// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcioqhwjpvynkxtptbyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjaW9xaHdqcHZ5bmt4dHB0YnlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NDIzMzcsImV4cCI6MjA3MjMxODMzN30.4kGO5viIDP8LwqghGV7mDlHsY9gNJEAkKLRnsG0ZOB8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});